[tool.poetry]
name = "jewel-db"
packages = [
    { include = "jewel_db" }
]
version = "0.1.0"
description = "A modern jewelry inventory system with AI integration"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
sqlmodel = "^0.0.16"
jinja2 = "^3.1.2"
tailwindcss = "*"
pillow = "^10.0.0"
python-dotenv = "^1.0.0"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
