name: 🛠 Lint, Format & Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-format:
    name: Pre-commit (Ruff, Black, etc.)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - run: |
          python -m pip install --upgrade pip pre-commit
          pre-commit run --all-files --show-diff-on-failure

  tests:
    name: Pytest & Coverage
    runs-on: ubuntu-latest
    needs: lint-format

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache-poetry
        with:
          path: ~/.cache/pypoetry
          key: poetry-v2-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --with dev

      - name: Run pytest
        run: |
          poetry run pytest --cov=jewel_db --cov-report=xml --cov-report=term-missing

      # Updated to v4
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
